// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOvWCiqYVVP7USJWUtILPBKe8glRZM0i4',
    appId: '1:210201460008:web:351a2e9cfaccf8e575641d',
    messagingSenderId: '210201460008',
    projectId: 'greenthumb-bfc2b',
    authDomain: 'greenthumb-bfc2b.firebaseapp.com',
    storageBucket: 'greenthumb-bfc2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3bWQs6FppS-0nSsw-wQrQi39khv8yNm8',
    appId: '1:210201460008:ios:9aa1b0c41b1ba0ed75641d',
    messagingSenderId: '210201460008',
    projectId: 'greenthumb-bfc2b',
    storageBucket: 'greenthumb-bfc2b.appspot.com',
    iosBundleId: 'com.example.greenThumb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3bWQs6FppS-0nSsw-wQrQi39khv8yNm8',
    appId: '1:210201460008:ios:9aa1b0c41b1ba0ed75641d',
    messagingSenderId: '210201460008',
    projectId: 'greenthumb-bfc2b',
    storageBucket: 'greenthumb-bfc2b.appspot.com',
    iosBundleId: 'com.example.greenThumb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOvWCiqYVVP7USJWUtILPBKe8glRZM0i4',
    appId: '1:210201460008:web:fd101da5de3ae67275641d',
    messagingSenderId: '210201460008',
    projectId: 'greenthumb-bfc2b',
    authDomain: 'greenthumb-bfc2b.firebaseapp.com',
    storageBucket: 'greenthumb-bfc2b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi0IJ1y0NFgLFPyB0FYK8h4oMJUJ05lLE',
    appId: '1:210201460008:android:b51931947480984975641d',
    messagingSenderId: '210201460008',
    projectId: 'greenthumb-bfc2b',
    storageBucket: 'greenthumb-bfc2b.appspot.com',
  );

}